name: linux

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libssh2-1-dev libssl-dev libfuse-dev libsmbclient-dev libsmbclient pkg-config
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy -- -Dwarnings
      - name: Run tests
        run: cargo test --features integration-tests --no-fail-fast
        env:
          RUST_LOG: trace
